### ISSUE TITLE
i bought the hsm book

### ISSUE THREAD

**Issue by gok-wolf** [hsdm-hub/hsdm#1]
i can not download the files with asci, grd, gri extensions...
please help.

**Comment by DamienGeorges** [comment]
on this github repository at https://github.com/hsdm-hub/hsdm/tree/master/data.
Hope that helps

**Comment by gok-wolf** [comment]
thanks...i could...

Damien Georges <notifications@github.com>, 15 Haz 2020 Pzt, 10:21 tarihinde
şunu yazdı:
